name: Github Pages

concurrency: 
  group: deployment
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-ipafont graphviz wget curl git
          version: 1.02
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openjdk-8-jre
          version: 1.02
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texinfo-tex texlive-latex-base texlive-xetex
          version: 1.02
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          make html
          make pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated
          commit_message: "Deploy Docs: ${{ github.event.head_commit.message }}"


